server:
  port: 8040
spring:
  application:
    name: microservice-hystrix-turbine2
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2
  appConfig: microservice-consumer-movie-ribbon-with-hystrix2
  instanceUrlSuffix:
    MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2: /ribbon/hystrix.stream

logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG